import {DAY,id,seed,validate,balance,paid,available,debt,schedule,complete,payment,convert} from './core.mjs';
import {sportPage,coachPage,sportAction} from './sports.mjs';
// ponytail: localStorage holds one browser's demo; use server transactions for shared real accounts.
const KEY='temp-crm-demo-v1', $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=d=>new Date(d+'T12:00:00+03:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',timeZone:'Europe/Moscow'});
const initials=c=>c.name.split(' ').slice(0,2).map(x=>x[0]).join('');
let state,blocked=false,selectedDay=DAY,clientTab='overview',submitAction=null,toastTimer;
function read(){try{const raw=localStorage.getItem(KEY),result=raw?validate(JSON.parse(raw)):seed();blocked=false;return result;}catch{blocked=true;return seed();}}
state=read();
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function change(text,fn){
 if(blocked)throw new Error('Сохранение недоступно. Экспортируйте данные; сброс демо удалит старую копию.');
 const raw=localStorage.getItem(KEY);
 if(raw&&JSON.parse(raw).revision!==state.revision)throw new Error('Данные изменены в другой вкладке. Обновите страницу и повторите действие.');
 const next=structuredClone(state);fn(next);next.revision++;next.audit.unshift({text,at:new Date().toISOString()});next.audit=next.audit.slice(0,100);validate(next);
 try{localStorage.setItem(KEY,JSON.stringify(next));}catch{throw new Error('Браузер не сохранил изменения. Освободите место или разрешите хранение данных.');}
 state=next;render();toast(text);
}
const client=id=>state.clients.find(x=>x.id===id);
const button=(text,action,value='',style='secondary')=>`<button class="button ${style}" data-action="${action}" data-id="${esc(value)}">${text}</button>`;
const badge=(text,type='')=>`<span class="badge ${type}">${text}</span>`;
const person=c=>`<span class="avatar tone-${state.clients.indexOf(c)%4}">${esc(initials(c))}</span><span class="person-name"><b>${esc(c.name)}</b><small>${esc(c.goal)}</small></span>`;
const empty=text=>`<div class="empty">${text}</div>`;
const header=(title,sub,actions='')=>`<div class="page-heading"><div><span class="eyebrow">Мой кабинет</span><h1>${title}</h1><p>${sub}</p></div><div class="heading-actions">${actions}</div></div>`;
function stats(){const receipts=state.payments.filter(x=>x.date.startsWith(DAY.slice(0,7))).reduce((n,x)=>n+x.amount,0);return `<div class="stats"><div><span>Активные клиенты</span><b>${state.clients.filter(x=>x.status==='active').length}</b><small>В работе сейчас</small></div><div><span>Занятия на сегодня</span><b>${state.sessions.filter(x=>x.start.startsWith(selectedDay)&&x.status!=='canceled').length}</b><small>${dateLabel(selectedDay)}</small></div><div><span>Продления на подходе</span><b>${state.clients.filter(c=>c.status==='active'&&available(state,c.id)<=2).length}</b><small>Осталось не более 2 занятий</small></div><div><span>Поступления в октябре</span><b>${money(receipts)}</b><small>Записанные оплаты</small></div></div>`;}
function sessionRow(x){const c=client(x.clientId),done=x.status==='done',cancel=x.status==='canceled';return `<div class="session-row ${cancel?'canceled':''}"><div class="session-time"><b>${x.start.slice(11)}</b><span>${x.duration} мин</span></div><a class="person" href="#client/${esc(c.id)}">${person(c)}</a><div class="session-type"><span>${esc(x.type)}</span>${badge(done?'Завершено':cancel?'Отменено':'По плану',done?'green':cancel?'gray':'')}</div><div class="session-actions">${done?button('Посмотреть','workout',x.id,'subtle'):cancel?'':button('Провести','workout',x.id,'')}${x.status==='planned'?button('⋯','session-menu',x.id,'icon-button'):''}</div></div>`;}
function taskList(){const ts=state.tasks.filter(t=>!t.done).sort((a,b)=>a.date.localeCompare(b.date));return ts.length?ts.map(t=>`<div class="task-row"><button class="task-check" data-action="task-done" data-id="${esc(t.id)}" aria-label="Выполнить задачу: ${esc(t.text)}"></button><div><b>${esc(t.text)}</b><span>${t.clientId?`<a href="#client/${esc(t.clientId)}">${esc(client(t.clientId).name)}</a> · `:''}${dateLabel(t.date)}</span></div></div>`).join(''):empty('Все задачи выполнены. Можно сосредоточиться на тренировках.');}
function attention(){const list=state.clients.filter(c=>c.status==='active'&&(available(state,c.id)<=2||debt(state,c.id)>0));return list.length?list.map(c=>`<a class="attention-row" href="#client/${esc(c.id)}"><span class="avatar tone-${state.clients.indexOf(c)%4}">${esc(initials(c))}</span><div><b>${esc(c.name)}</b><small>${debt(state,c.id)>0?'К оплате '+money(debt(state,c.id)):'Осталось занятий: '+available(state,c.id)}</small></div><span>↗</span></a>`).join(''):empty('Пакеты и оплаты в порядке.');}
function today(){const ss=state.sessions.filter(x=>x.start.startsWith(selectedDay)).sort((a,b)=>a.start.localeCompare(b.start));return header('Держим темп.','Занятия, клиенты и следующие действия — перед глазами.',button('+ Запланировать занятие','session-new','',''))+stats()+`<div class="dashboard-grid"><section class="panel schedule-panel"><div class="panel-head"><div><h2>Расписание дня</h2><span>${dateLabel(selectedDay)} · ${ss.filter(x=>x.status!=='canceled').length} занятия</span></div><div class="date-controls"><button class="icon-button" data-action="day-prev" aria-label="Предыдущий день">←</button><input id="day" type="date" value="${selectedDay}" aria-label="День расписания"><button class="icon-button" data-action="day-next" aria-label="Следующий день">→</button></div></div>${ss.map(sessionRow).join('')||empty('На этот день нет занятий. Запланируйте первое.')}</section><section class="panel attention-panel"><div class="panel-head"><h2>Нужен контакт</h2>${badge('Пакеты и оплаты','gray')}</div>${attention()}</section><section class="panel tasks-panel"><div class="panel-head"><div><h2>Следующие действия</h2><span>Ничего важного не потеряется</span></div>${button('+ Задача','task-new','','subtle')}</div>${taskList()}</section><section class="daily-note"><span class="eyebrow">Один рабочий цикл</span><h2>От хорошей тренировки<br>к следующей встрече.</h2><p>Запишите результаты, проверьте остаток пакета и договоритесь о продолжении.</p><a href="#clients">Перейти к клиентам ↗</a><div class="track-art" aria-hidden="true"><i></i><i></i><i></i></div></section></div>`;}
function clients(){return header('Клиенты','История занятий, пакеты и договорённости в одной карточке.',button('+ Добавить клиента','client-new','',''))+`<section class="panel"><div class="panel-head"><h2>Ваша команда</h2><label class="search"><span aria-hidden="true">⌕</span><input id="client-search" placeholder="Найти клиента" aria-label="Поиск клиентов"></label></div><div class="table-wrap"><table><thead><tr><th>Клиент</th><th>Статус</th><th>Занятия</th><th>К оплате</th><th>Следующая встреча</th></tr></thead><tbody>${state.clients.map(c=>{const next=state.sessions.filter(x=>x.clientId===c.id&&x.status==='planned'&&x.start.slice(0,10)>=DAY).sort((a,b)=>a.start.localeCompare(b.start))[0];return `<tr data-client-name="${esc(c.name.toLowerCase())}"><td><a class="person" href="#client/${esc(c.id)}">${person(c)}</a></td><td>${badge(c.status==='active'?'В работе':'Пауза',c.status==='active'?'green':'gray')}</td><td><span class="balance ${available(state,c.id)<=2?'low':''}">${available(state,c.id)}</span> осталось</td><td>${debt(state,c.id)?`<b class="debt">${money(debt(state,c.id))}</b>`:'<span class="muted">Всё оплачено</span>'}</td><td>${next?dateLabel(next.start.slice(0,10))+' · '+next.start.slice(11):'—'}</td></tr>`;}).join('')}</tbody></table></div><div id="search-empty" class="empty" hidden>Клиентов с таким именем нет.</div></section>`;}
function progress(c){const records=state.sessions.filter(x=>x.clientId===c.id&&x.status==='done'&&x.exercises.some(e=>e.name==='Приседания')).sort((a,b)=>a.start.localeCompare(b.start));if(records.length<2)return empty('После нескольких тренировок здесь появится динамика рабочих весов.');const vals=records.map(r=>r.exercises.find(e=>e.name==='Приседания').weight),max=Math.max(1,...vals),points=vals.map((v,i)=>`${20+i/(vals.length-1)*470},${145-v/max*115}`).join(' ');return `<div class="progress-heading"><div><h3>Приседания</h3><span>Рабочий вес по записанным тренировкам</span></div><b>${vals.at(-1)} <small>кг</small></b></div><svg viewBox="0 0 520 175" role="img" aria-label="Рабочие веса: ${vals.join(', ')} килограммов"><path d="M20 145H500 M20 90H500 M20 35H500" stroke="#e4ebe8"/><polyline points="${points}" fill="none" stroke="#255b4e" stroke-width="3"/>${vals.map((v,i)=>`<circle cx="${20+i/(vals.length-1)*470}" cy="${145-v/max*115}" r="4" fill="#255b4e"/><text x="${20+i/(vals.length-1)*470}" y="168" text-anchor="middle" font-size="10" fill="#68766f">${records[i].start.slice(8,10)}.${records[i].start.slice(5,7)}</text>`).join('')}</svg><div class="progress-values">${vals.map(v=>v+' кг').join(' → ')}</div>`;}
function packages(c){return state.packages.filter(p=>p.clientId===c.id).map(p=>`<div class="package-card"><div><b>Пакет на ${p.count} занятий</b><span>Добавлен ${dateLabel(p.date)}</span></div>${badge(balance(state,p)+' осталось',balance(state,p)<=2?'amber':'green')}<div class="package-meter"><i style="width:${balance(state,p)/p.count*100}%"></i></div><div class="package-details"><span>${money(p.price)}</span><span>${paid(state,p)===p.price?'Оплачен полностью':'К оплате '+money(p.price-paid(state,p))}</span></div>${paid(state,p)<p.price?button('Записать оплату','payment-new',p.id,'subtle'):''}</div>`).join('')||empty('Пакетов пока нет. Добавьте первый, чтобы проводить занятия.');}
function clientPage(c){if(!c)return header('Клиент не найден','Вернитесь к списку клиентов.')+`<a href="#clients">Все клиенты</a>`;const ps=state.packages.filter(p=>p.clientId===c.id),payments=state.payments.filter(x=>ps.some(p=>p.id===x.packageId)),ss=state.sessions.filter(x=>x.clientId===c.id).sort((a,b)=>b.start.localeCompare(a.start));let body;
 if(clientTab==='training')body=`<section class="panel"><div class="panel-head"><h2>История и планы</h2>${button('+ Занятие','session-new',c.id,'')}</div>${ss.map(x=>`<div class="history-date">${dateLabel(x.start.slice(0,10))}</div>${sessionRow(x)}`).join('')||empty('Запланируйте первую тренировку.')}</section>`;
 else if(clientTab==='payments')body=`<div class="client-grid"><section class="panel"><div class="panel-head"><h2>Пакеты занятий</h2>${button('+ Пакет','package-new',c.id,'')}</div><div class="padded">${packages(c)}</div></section><section class="panel"><div class="panel-head"><h2>История оплат</h2></div>${paymentRows(payments)}</section></div>`;
 else body=`<div class="client-grid"><section class="panel"><div class="panel-head"><h2>Прогресс клиента</h2>${badge('Фактические записи','gray')}</div><div class="padded">${progress(c)}</div></section><section class="panel"><div class="panel-head"><h2>Пакеты занятий</h2>${button('+ Пакет','package-new',c.id,'subtle')}</div><div class="padded">${packages(c)}</div></section><section class="panel"><div class="panel-head"><h2>Ближайшие занятия</h2>${button('+ Занятие','session-new',c.id,'subtle')}</div>${ss.filter(x=>x.status==='planned').reverse().map(sessionRow).join('')||empty('Ближайших занятий нет.')}</section><section class="panel"><div class="panel-head"><h2>Заметки и договорённости</h2>${button('Изменить','client-edit',c.id,'subtle')}</div><div class="padded"><p class="client-note">${esc(c.note)||'Пока нет заметок.'}</p><div class="contact-line">${esc(c.contact)||'Контакт не указан'}</div>${button('+ Задача','task-new',c.id,'subtle')}</div></section></div>`;
 return `<a class="back-link" href="#clients">← Все клиенты</a><div class="client-heading"><div class="person">${person(c)}</div><div class="heading-actions">${button('Изменить','client-edit',c.id,'secondary')}${button('Запланировать','session-new',c.id,'')}</div></div><div class="client-summary">${badge(c.status==='active'?'В работе':'Пауза',c.status==='active'?'green':'gray')}<span><b>${available(state,c.id)}</b> занятий осталось</span><span>К оплате: <b>${money(debt(state,c.id))}</b></span></div><div class="tabs" role="group" aria-label="Раздел карточки">${[['overview','Обзор'],['training','Тренировки'],['payments','Пакеты и оплаты']].map(([key,label])=>`<button class="${clientTab===key?'selected':''}" data-action="client-tab" data-id="${key}" aria-pressed="${clientTab===key}">${label}</button>`).join('')}</div>${body}`;
}
function addDays(d,n){const date=new Date(d+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);}
function calendar(){const days=Array.from({length:7},(_,i)=>addDays(selectedDay,i));return header('Расписание','Семь дней вперёд. Переносы и отмены сохраняются в истории.',button('+ Занятие','session-new','',''))+`<div class="calendar-controls">${button('← Неделя','week-prev','','secondary')}<b>${dateLabel(days[0])} — ${dateLabel(days[6])}</b>${button('Неделя →','week-next','','secondary')}</div><div class="week-wrap"><div class="week">${days.map(d=>`<section class="week-day ${d===DAY?'is-today':''}"><div class="week-label"><span>${new Date(d+'T12:00:00+03:00').toLocaleDateString('ru-RU',{weekday:'short',timeZone:'Europe/Moscow'})}</span><b>${d.slice(8)}</b></div>${state.sessions.filter(x=>x.start.startsWith(d)&&x.status!=='canceled').sort((a,b)=>a.start.localeCompare(b.start)).map(x=>`<button class="week-session ${x.status==='done'?'done':''}" data-action="session-menu" data-id="${esc(x.id)}"><span>${x.start.slice(11)} · ${x.duration} мин</span><b>${esc(client(x.clientId).name)}</b><small>${esc(x.type)}</small>${x.status==='done'?'<small>Завершено ✓</small>':''}</button>`).join('')||'<p class="week-empty">Свободный день</p>'}<button class="add-slot" data-action="session-day" data-id="${d}">+ Занятие</button></section>`).join('')}</div></div>`;}
const stages=[['new','Новые'],['contact','На связи'],['trial','Пробное'],['won','Клиенты'],['lost','Отказ']];
function leads(){return header('Продажи','Каждая заявка — понятный следующий шаг.',button('+ Новая заявка','lead-new','',''))+`<div class="pipeline-wrap"><div class="pipeline">${stages.map(([stage,label])=>`<section class="pipeline-column"><h2>${label}<span>${state.leads.filter(l=>l.stage===stage).length}</span></h2>${state.leads.filter(l=>l.stage===stage).map(l=>`<div class="lead-card"><span class="lead-source">${esc(l.source)}</span><h3>${esc(l.name)}</h3><p>${esc(l.goal)}</p>${l.contact?`<small>${esc(l.contact)}</small>`:''}${l.clientId?`<a href="#client/${esc(l.clientId)}">Карточка клиента ↗</a>`:`<label class="stage-label">Этап<select data-lead="${esc(l.id)}" aria-label="Этап заявки ${esc(l.name)}">${stages.filter(([k])=>k!=='won').map(([k,label])=>`<option value="${k}" ${stage===k?'selected':''}>${label}</option>`).join('')}</select></label>${button('В клиенты →','lead-convert',l.id,'subtle')}`}</div>`).join('')}<button class="add-slot" data-action="lead-stage" data-id="${stage}">+ Заявка</button></section>`).join('')}</div></div>`;}
function paymentRows(rows){return rows.length?rows.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>{const p=state.packages.find(p=>p.id===x.packageId),c=client(p.clientId);return `<div class="payment-row"><div><a href="#client/${esc(c.id)}">${esc(c.name)}</a><span>${dateLabel(x.date)} · ${esc(x.method)}</span></div><b>${money(x.amount)}</b><button class="icon-button" data-action="payment-void" data-id="${esc(x.id)}" aria-label="Отменить запись оплаты ${esc(c.name)} на ${x.amount} рублей">×</button></div>`;}).join(''):empty('Оплат пока нет. Добавьте пакет и запишите поступление.');}
function finance(){const total=state.payments.reduce((n,x)=>n+x.amount,0),owed=state.clients.reduce((n,c)=>n+debt(state,c.id),0);return header('Оплаты','Поступления и остатки к оплате. Это учёт, а не приём платежей.',button('+ Записать оплату','payment-new','',''))+`<div class="finance-stats"><div><span>Все записанные поступления</span><b>${money(total)}</b></div><div><span>Осталось оплатить</span><b>${money(owed)}</b></div><div><span>Пакетов с задолженностью</span><b>${state.packages.filter(p=>paid(state,p)<p.price).length}</b></div></div><div class="client-grid"><section class="panel"><div class="panel-head"><h2>Последние поступления</h2></div>${paymentRows(state.payments)}</section><section class="panel"><div class="panel-head"><h2>К оплате</h2></div>${state.clients.filter(c=>debt(state,c.id)>0).map(c=>`<div class="payment-row"><a href="#client/${esc(c.id)}">${esc(c.name)}</a><b>${money(debt(state,c.id))}</b>${button('Оплата','payment-client',c.id,'subtle')}</div>`).join('')||empty('Все пакеты оплачены.')}</section></div><details class="audit"><summary>История изменений</summary>${state.audit.map(x=>`<p><span>${esc(new Date(x.at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'}))}</span> ${esc(x.text)}</p>`).join('')||'<p>Здесь появятся ваши изменения.</p>'}</details>`;}
function render(){const route=location.hash.slice(1)||'sport',key=route.startsWith('client/')?'clients':route;
 const nav=[['sport','↗','Подготовка'],['coach','◈','Профиль тренера'],['today','◷','Рабочий день'],['clients','◉','Клиенты'],['calendar','▦','Расписание'],['leads','↗','Продажи'],['finance','₽','Оплаты']];
 $('#nav').innerHTML=nav.map(([k,icon,label])=>`<a href="#${k}" class="${key===k?'active':''}" ${key===k?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}${k==='leads'?`<small>${state.leads.filter(l=>!['won','lost'].includes(l.stage)).length}</small>`:''}</a>`).join('');
 $('#breadcrumb').textContent='Мой кабинет / '+(nav.find(x=>x[0]===key)?.[2]||'Сегодня');
 $('#save-status').textContent=blocked?'Сохранение недоступно':'Демо · данные в браузере';
 $('#content').innerHTML=route==='sport'?sportPage(state):route==='coach'?coachPage(state):route.startsWith('client/')?clientPage(client(route.slice(7))):({today,clients,calendar,leads,finance}[route]||today)();
}
function field(label,name,value='',type='text',more=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${more}></label>`;}
function clientSelect(value=''){return `<label>Клиент<select name="clientId" required>${state.clients.map(c=>`<option value="${esc(c.id)}" ${c.id===value?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`;}
function open(title,fields,fn,label='Сохранить'){if($('#dialog').open)$('#dialog').close();$('#dialog-title').textContent=title;$('#fields').innerHTML=fields;$('#form-error').textContent='';$('#submit').textContent=label;$('#submit').hidden=!fn;submitAction=fn;$('#dialog').showModal();}
function clientForm(editing){const c=editing?client(editing):{name:'',goal:'',contact:'',note:'',status:'active'};open(editing?'Изменить клиента':'Новый клиент',field('Имя','name',c.name,'text','required maxlength="80" autocomplete="off"')+field('Цель','goal',c.goal,'text','maxlength="200"')+field('Контакт','contact',c.contact,'text','maxlength="120"')+`<label>Заметки<textarea name="note" maxlength="2000">${esc(c.note)}</textarea></label><label>Статус<select name="status"><option value="active" ${c.status==='active'?'selected':''}>В работе</option><option value="paused" ${c.status==='paused'?'selected':''}>Пауза</option></select></label>`,f=>change(editing?'Карточка клиента обновлена':'Клиент добавлен',s=>{const vals={name:f.get('name').trim(),goal:f.get('goal').trim(),contact:f.get('contact').trim(),note:f.get('note').trim(),status:f.get('status')};if(editing)Object.assign(s.clients.find(x=>x.id===editing),vals);else s.clients.push({id:id(),...vals});}));}
function sessionForm(c='',editing=null,day=selectedDay){if(!state.clients.length)return toast('Сначала добавьте клиента.');const x=editing?state.sessions.find(x=>x.id===editing):null;open(x?'Перенести занятие':'Запланировать занятие',clientSelect(x?.clientId||c)+field('Дата и время','start',x?.start||day+'T10:00','datetime-local','required')+`<div class="form-grid">${field('Продолжительность, мин','duration',x?.duration||60,'number','min="15" max="240" step="1" required')}${field('Тип тренировки','type',x?.type||'Силовая','text','required maxlength="80"')}</div>`,f=>change(x?'Занятие перенесено':'Занятие запланировано',s=>schedule(s,{clientId:f.get('clientId'),start:f.get('start'),duration:Number(f.get('duration')),type:f.get('type').trim()},editing)));}
function packageForm(c){open('Добавить пакет',clientSelect(c)+`<div class="form-grid">${field('Количество занятий','count',8,'number','min="1" max="1000" step="1" required')}${field('Стоимость, ₽','price',24000,'number','min="0" max="100000000" step="1" required')}</div>`+field('Оплачено сейчас, ₽','amount',0,'number','min="0" max="100000000" step="1" required')+field('Дата','date',DAY,'date','required'),f=>change('Пакет добавлен',s=>{const p={id:id(),clientId:f.get('clientId'),count:Number(f.get('count')),price:Number(f.get('price')),date:f.get('date')};s.packages.push(p);const amount=Number(f.get('amount'));if(amount)payment(s,p.id,amount,'Перевод',p.date);}));}
function paymentForm(pId='',cId=''){const ps=state.packages.filter(p=>paid(state,p)<p.price&&(!cId||p.clientId===cId));if(!ps.length)return toast('Все пакеты оплачены. Сначала добавьте новый пакет.');const target=ps.find(p=>p.id===pId)||ps[0];open('Записать оплату',`<label>Пакет<select name="packageId" id="package-select">${ps.map(p=>`<option value="${esc(p.id)}" ${p.id===target.id?'selected':''}>${esc(client(p.clientId).name)} · ${p.count} занятий · к оплате ${money(p.price-paid(state,p))}</option>`).join('')}</select></label>`+field('Сумма, ₽','amount',target.price-paid(state,target),'number','min="1" max="100000000" step="1" required')+`<div class="form-grid">${field('Дата','date',DAY,'date','required')}<label>Способ<select name="method"><option>Перевод</option><option>Наличные</option><option>Карта</option></select></label></div>`,f=>change('Оплата записана',s=>payment(s,f.get('packageId'),Number(f.get('amount')),f.get('method'),f.get('date'))));$('#package-select').addEventListener('change',e=>{const p=ps.find(p=>p.id===e.target.value);$('#form [name="amount"]').value=p.price-paid(state,p);});}
function exerciseRow(e={},readonly=false){return `<div class="exercise-row">${field('Упражнение','exercise-name',e.name||'','text',`required maxlength="80" ${readonly?'readonly':''}`)}${field('Подходы','sets',e.sets??3,'number',`required min="1" max="50" step="1" ${readonly?'readonly':''}`)}${field('Повторы','reps',e.reps??10,'number',`required min="1" max="1000" step="1" ${readonly?'readonly':''}`)}${field('Вес, кг','weight',e.weight??0,'number',`required min="0" max="1000" step="0.5" ${readonly?'readonly':''}`)}${!readonly?'<button type="button" class="icon-button remove-exercise" aria-label="Удалить упражнение">×</button>':''}</div>`;}
function workout(xId){const x=state.sessions.find(x=>x.id===xId),c=client(x.clientId),done=x.status==='done';let previous=state.sessions.filter(t=>t.clientId===c.id&&t.status==='done').sort((a,b)=>b.start.localeCompare(a.start))[0];const exercises=done?x.exercises:previous?.exercises||[{name:'Приседания',sets:3,reps:10,weight:20},{name:'Тяга блока',sets:3,reps:12,weight:25}];open(done?'Результаты тренировки':'Провести тренировку',`<div class="workout-client"><b>${esc(c.name)}</b><span>${dateLabel(x.start.slice(0,10))} · ${x.start.slice(11)} · ${esc(x.type)}</span></div>${!done?'<p class="form-hint">Завершение спишет одно занятие из доступного пакета. Предыдущие результаты подставлены как отправная точка.</p>':''}<div id="exercises">${exercises.map(e=>exerciseRow(e,done)).join('')}</div>${!done?'<button type="button" class="button subtle" id="exercise-add">+ Упражнение</button>':''}<label>Комментарий<textarea name="note" maxlength="2000" ${done?'readonly':''}>${esc(done?x.note:'')}</textarea></label>${done?`<button type="button" class="button danger" data-action="workout-undo" data-id="${esc(x.id)}">Отменить завершение и вернуть занятие</button>`:''}`,done?null:f=>{const es=[...$('#exercises').children].map(row=>({name:row.querySelector('[name="exercise-name"]').value.trim(),sets:Number(row.querySelector('[name="sets"]').value),reps:Number(row.querySelector('[name="reps"]').value),weight:Number(row.querySelector('[name="weight"]').value)}));if(!es.length)throw new Error('Добавьте хотя бы одно упражнение.');change('Тренировка завершена · списано 1 занятие',s=>complete(s,x.id,es,f.get('note').trim()));},'Завершить тренировку');if(!done)$('#exercise-add').onclick=()=>{if($('#exercises').children.length>=30)return toast('В одной тренировке не более 30 упражнений.');$('#exercises').insertAdjacentHTML('beforeend',exerciseRow());};}
function taskForm(c=''){open('Следующее действие',field('Что нужно сделать','text','','text','required maxlength="300"')+field('Срок','date',DAY,'date','required')+`<label>Клиент<select name="clientId"><option value="">Без привязки</option>${state.clients.map(x=>`<option value="${esc(x.id)}" ${x.id===c?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`,f=>change('Задача добавлена',s=>s.tasks.push({id:id(),text:f.get('text').trim(),date:f.get('date'),clientId:f.get('clientId')||null,done:false})));}
function leadForm(stage='new'){open('Новая заявка',field('Имя','name','','text','required maxlength="80"')+field('Контакт','contact','','text','maxlength="120"')+field('Запрос клиента','goal','','text','maxlength="200"')+field('Источник','source','Рекомендация','text','maxlength="80" required'),f=>change('Заявка добавлена',s=>s.leads.push({id:id(),name:f.get('name').trim(),contact:f.get('contact').trim(),goal:f.get('goal').trim(),source:f.get('source').trim(),stage:stage==='won'?'new':stage,date:DAY,clientId:null})));}
function exportData(){const raw=blocked?localStorage.getItem(KEY):JSON.stringify(state,null,2);if(raw===null)throw new Error('Сохранённая копия не найдена.');const blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=blocked?'temp-crm-recovery.json':'temp-crm-demo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(blocked?'Исходная копия экспортирована для восстановления':'Копия данных экспортирована');}
document.addEventListener('click',e=>{
 if(e.target.closest('.remove-exercise')){e.target.closest('.exercise-row').remove();return;}
 const el=e.target.closest('[data-action]');if(!el)return;const key=el.dataset.action,value=el.dataset.id;
 try{
  if(sportAction(key,value,state,open,change))return;
  switch(key){
   case 'client-new':clientForm();break;case 'client-edit':clientForm(value);break;
   case 'session-new':sessionForm(value);break;case 'session-day':sessionForm('',null,value);break;
   case 'package-new':packageForm(value);break;case 'payment-new':paymentForm(value);break;case 'payment-client':paymentForm('',value);break;
   case 'workout':workout(value);break;case 'task-new':taskForm(value);break;
   case 'task-done':change('Задача выполнена',s=>{s.tasks.find(t=>t.id===value).done=true;});break;
   case 'lead-new':leadForm();break;case 'lead-stage':leadForm(value);break;
   case 'lead-convert':{let newId;change('Заявка переведена в клиента',s=>{newId=convert(s,value);});clientTab='overview';location.hash='client/'+newId;break;}
   case 'client-tab':clientTab=value;render();break;
   case 'day-prev':case 'day-next':selectedDay=addDays(selectedDay,key==='day-prev'?-1:1);render();break;
   case 'week-prev':case 'week-next':selectedDay=addDays(selectedDay,key==='week-prev'?-7:7);render();break;
   case 'session-menu':{const x=state.sessions.find(x=>x.id===value);open('Занятие · '+client(x.clientId).name,`<p>${dateLabel(x.start.slice(0,10))} · ${x.start.slice(11)} · ${x.duration} мин</p><div class="menu-actions">${button(x.status==='done'?'Результаты':'Провести тренировку','workout',value,'')}${x.status==='planned'?button('Перенести','reschedule',value)+button('Отменить занятие','session-cancel',value,'danger'):''}</div>`,null);break;}
   case 'reschedule':sessionForm('',value);break;
   case 'session-cancel':if(confirm('Отменить занятие? Оно останется в истории, пакет не изменится.')){change('Занятие отменено',s=>{const x=s.sessions.find(x=>x.id===value);if(x.status!=='planned')throw new Error('Можно отменить только запланированное занятие.');x.status='canceled';});$('#dialog').close();}break;
   case 'workout-undo':if(confirm('Вернуть занятие в пакет и снять отметку о завершении?')){change('Завершение отменено · занятие возвращено',s=>{const x=s.sessions.find(x=>x.id===value);if(x.status!=='done')throw new Error('Занятие уже не завершено.');x.status='planned';x.packageId=null;});$('#dialog').close();}break;
   case 'payment-void':if(confirm('Отменить запись этой оплаты? Остаток к оплате увеличится. Это не возврат денег.'))change('Запись оплаты отменена',s=>{s.payments=s.payments.filter(x=>x.id!==value);});break;
   case 'export':exportData();break;case 'import':$('#import-file').click();break;
   case 'reset':if(confirm('Удалить все изменения демоверсии и восстановить вымышленные данные? Экспортируйте их заранее.')){localStorage.removeItem(KEY);blocked=false;state=seed();selectedDay=DAY;render();toast('Демонстрационные данные восстановлены');}break;
  }
 }catch(err){if($('#dialog').open)$('#form-error').textContent=err.message;else toast(err.message);}
});
$('#form').addEventListener('submit',e=>{e.preventDefault();try{if(submitAction)submitAction(new FormData(e.target));$('#dialog').close();}catch(err){$('#form-error').textContent=err.message;}});
$('#dialog-close').onclick=$('#dialog-cancel').onclick=()=>$('#dialog').close();
document.addEventListener('change',e=>{if(e.target.id==='day'){if(e.target.value){selectedDay=e.target.value;render();}}if(e.target.dataset.lead){try{change('Этап заявки обновлён',s=>{s.leads.find(l=>l.id===e.target.dataset.lead).stage=e.target.value;});}catch(err){toast(err.message);render();}}});
document.addEventListener('input',e=>{if(e.target.id==='client-search'){const term=e.target.value.toLowerCase().trim(),rows=[...document.querySelectorAll('[data-client-name]')];rows.forEach(r=>r.hidden=!r.dataset.clientName.includes(term));$('#search-empty').hidden=rows.some(r=>!r.hidden);}});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>2e6)throw new Error('Файл слишком большой. Максимум 2 МБ.');const imported=validate(JSON.parse(await file.text()));if(confirm('Заменить данные в этом браузере содержимым файла? Сначала экспортируйте текущую копию.'))change('Данные импортированы',s=>{const revision=s.revision;delete s.sports;Object.assign(s,structuredClone(imported));s.revision=revision;});}catch(err){toast(err.message);}});
window.addEventListener('hashchange',()=>{clientTab='overview';render();window.scrollTo(0,0);});
window.addEventListener('storage',e=>{if(e.key===KEY){state=read();render();toast('Данные обновлены из другой вкладки');}});
render();if(blocked)toast('Не удалось прочитать сохранение. Исходная копия не перезаписана.');
