import assert from 'node:assert/strict';
import {seedSports,validateSports,ensureSports,previousFocus} from './sports.mjs';
import {materials,filterMaterials,validateKnowledge} from './knowledge.mjs';
import {seed,validate,balance,paid,schedule,complete,payment,convert} from './core.mjs';
const s=seed(),p=s.packages[0];
assert.equal(balance(s,p),1);
assert.throws(()=>schedule(s,{clientId:'c0',start:'2026-10-01T09:30',duration:60,type:'Силовая'}),/уже есть/);
complete(s,'today0',[{name:'Приседания',sets:3,reps:10,weight:35}],'Хорошая тренировка');
assert.equal(balance(s,p),0);
assert.throws(()=>complete(s,'today0',[],'Повтор'),/уже завершено/);
schedule(s,{clientId:'c0',start:'2026-10-01T10:00',duration:60,type:'Силовая'});
const newSession=s.sessions.at(-1);
assert.throws(()=>complete(s,newSession.id,[{name:'Тяга',sets:3,reps:10,weight:20}],''),/Нет доступных/);
s.sessions.find(x=>x.id==='today0').status='planned';s.sessions.find(x=>x.id==='today0').packageId=null;
assert.equal(balance(s,p),1);
const owed=s.packages[3];assert.equal(paid(s,owed),12000);
assert.throws(()=>payment(s,owed.id,12001,'Перевод','2026-10-01'),/больше остатка/);
payment(s,owed.id,12000,'Перевод','2026-10-01');assert.equal(paid(s,owed),24000);
const count=s.clients.length,c=convert(s,'l0');assert.equal(s.clients.length,count+1);assert.equal(convert(s,'l0'),c);assert.equal(s.clients.length,count+1);
assert.doesNotThrow(()=>validate(s));
const broken=structuredClone(s);broken.sessions[0].clientId='unknown';assert.throws(()=>validate(broken));
const invalidDate=structuredClone(s);invalidDate.packages[0].date='2026-02-30';assert.throws(()=>validate(invalidDate));
console.log('Passed: package balance, no double completion/overdraft, restoration, scheduling conflicts, exact payments, idempotent lead conversion, import references/dates.');
const sport=seedSports();assert.doesNotThrow(()=>validateSports(sport));s.sports=sport;assert.doesNotThrow(()=>validate(s));
const badSport=structuredClone(sport);badSport.spaces.run.sessions[0].volume=-1;assert.throws(()=>validateSports(badSport));
const missingResult=structuredClone(sport);missingResult.spaces.swim.sessions[0].status='done';assert.throws(()=>validateSports(missingResult));
const badSportDate=structuredClone(sport);badSportDate.spaces.football.sessions[0].date='2026-02-30';assert.throws(()=>validateSports(badSportDate));
console.log('Passed: sports import validation, negative volume, missing results, invalid dates.');
const filters={sport:'swim',type:'template',query:'кроль',favorites:false};assert.equal(filterMaterials(s,filters).length,1);
s.knowledge={custom:[],favorites:['kb-run-1']};assert.doesNotThrow(()=>validate(s));assert.equal(filterMaterials(s,{sport:'all',type:'all',query:'',favorites:true}).length,1);
assert.throws(()=>validateKnowledge({custom:[],favorites:['missing']}));
const badMaterial={...materials[0],id:'custom',source:'javascript:alert(1)'};assert.throws(()=>validateKnowledge({custom:[badMaterial],favorites:[]}));
assert.equal(materials.filter(x=>x.type==='exercise').length,7);console.log('Passed: library search/filter, favorites references, untrusted source rejected.');

const legacy=seedSports();delete legacy.spaces.tennis;assert.doesNotThrow(()=>validateSports(legacy));const migrated={sports:legacy};ensureSports(migrated);assert.equal(migrated.sports.spaces.tennis.sessions.length,3);
const a=migrated.sports.spaces.run.sessions[0];a.status='done';a.result='Серия выполнена';a.review={outcome:'changed',reason:'Изменили дистанцию',observation:'Потеря темпа',nextFocus:'Проверить темп'};assert.equal(previousFocus(migrated.sports.spaces.run.sessions,migrated.sports.spaces.run.sessions[1]).id,a.id);assert.equal(previousFocus(migrated.sports.spaces.run.sessions,a),undefined);assert.doesNotThrow(()=>validateSports(migrated.sports));a.review.reason='';assert.throws(()=>validateSports(migrated.sports));a.review.reason='Причина';a.status='skipped';a.review.outcome='skipped';assert.doesNotThrow(()=>validateSports(migrated.sports));
const own={...materials[0],id:'own-method',method:{levels:'L1',technique:'Критерий',mistakes:'Ошибка',easier:'Упростить',video:'javascript:alert(1)'}};assert.throws(()=>validateKnowledge({custom:[own],favorites:[]}));own.method.video='https://example.com/video';assert.doesNotThrow(()=>validateKnowledge({custom:[own],favorites:[]}));console.log('Passed: legacy migration, chronological training memory, review consistency, safe video links.');
