import assert from 'node:assert/strict';
import {seed,validate,balance,paid,schedule,complete,payment,convert} from './core.mjs';
const s=seed(),p=s.packages[0];
assert.equal(balance(s,p),1);
assert.throws(()=>schedule(s,{clientId:'c0',start:'2026-10-01T09:30',duration:60,type:'Силовая'}),/уже есть/);
complete(s,'today0',[{name:'Приседания',sets:3,reps:10,weight:35}],'Хорошая тренировка');
assert.equal(balance(s,p),0);
assert.throws(()=>complete(s,'today0',[],'Повтор'),/уже завершено/);
schedule(s,{clientId:'c0',start:'2026-10-01T10:00',duration:60,type:'Силовая'});
const newSession=s.sessions.at(-1);
assert.throws(()=>complete(s,newSession.id,[{name:'Тяга',sets:3,reps:10,weight:20}],''),/Нет доступных/);
s.sessions.find(x=>x.id==='today0').status='planned';s.sessions.find(x=>x.id==='today0').packageId=null;
assert.equal(balance(s,p),1);
const owed=s.packages[3];assert.equal(paid(s,owed),12000);
assert.throws(()=>payment(s,owed.id,12001,'Перевод','2026-10-01'),/больше остатка/);
payment(s,owed.id,12000,'Перевод','2026-10-01');assert.equal(paid(s,owed),24000);
const count=s.clients.length,c=convert(s,'l0');assert.equal(s.clients.length,count+1);assert.equal(convert(s,'l0'),c);assert.equal(s.clients.length,count+1);
assert.doesNotThrow(()=>validate(s));
const broken=structuredClone(s);broken.sessions[0].clientId='unknown';assert.throws(()=>validate(broken));
const invalidDate=structuredClone(s);invalidDate.packages[0].date='2026-02-30';assert.throws(()=>validate(invalidDate));
console.log('Passed: package balance, no double completion/overdraft, restoration, scheduling conflicts, exact payments, idempotent lead conversion, import references/dates.');
