import {sports,ensureSports,esc,btn,field} from './sports.mjs';
const fifa='https://www.fifatrainingcentre.com/en/practice/elite-sessions/in-possession/john-peacock-passing-and-receiving.php';
// ponytail: nine editorial demo cards; trainer materials live in the browser until server accounts are added.
export const materials=[
 {id:'kb-run-1',sport:'run',type:'exercise',title:'Беговые интервалы',summary:'Карточка повторного отрезка: дистанция, темп, отдых и факт выполнения.',body:'Задача: описать серию отрезков так, чтобы спортсмен понимал каждое повторение.\n\nВ карточке серии запишите длину отрезка, число повторений, целевой темп и формат отдыха. Разминку и заключительную часть вынесите отдельными блоками.\n\nПосле занятия запишите фактическое время каждого отрезка и комментарий спортсмена. Количество повторений и интенсивность задаёт тренер.',equipment:'Размеченная дистанция · секундомер',volume:0},
 {id:'kb-run-2',sport:'run',type:'exercise',title:'Ровный бег',summary:'Один непрерывный блок с заданной дистанцией и ориентиром по усилию.',body:'Задача: зафиксировать непрерывный беговой блок.\n\nУкажите дистанцию, поверхность и понятный спортсмену ориентир интенсивности. Зафиксируйте, входит ли разминка в общий объём.\n\nДля сравнения тренировок сохраняйте фактическую дистанцию, время и условия. Одинаковая дистанция в разных условиях не означает одинаковую нагрузку.',equipment:'Маршрут · часы',volume:0},
 {id:'kb-football-1',sport:'football',type:'exercise',title:'Передача и приём в движении',summary:'Работа в парах: обзор пространства, направление первого касания и точность передачи.',body:'Задача: принимать мяч с возможностью продолжить движение и выбрать следующую передачу.\n\nИгроки работают в парах с мячом внутри размеченной зоны, перемещаются и учитывают других участников. Перед приёмом осматривают пространство; первое касание готовит следующее действие.\n\nТренер наблюдает за направлением первого касания и своевременностью передачи. Размер зоны, число игроков и ограничения касаний адаптируются к группе.',equipment:'Мячи · фишки',volume:0,source:fifa},
 {id:'kb-football-2',sport:'football',type:'exercise',title:'Владение 4 × 4 + 3',summary:'Две команды по четыре игрока и три нейтральных участника.',body:'Задача: использовать свободного партнёра при продвижении мяча.\n\nНейтральные игроки помогают команде с мячом, соперник пытается перехватить передачу. Для исходной схемы требуется 11 участников.\n\nНаблюдайте, как игроки выбирают направление передачи и открываются в свободное пространство. Размер площадки и ограничения касаний назначает тренер.',equipment:'11 игроков · мячи · манишки · фишки',volume:0,source:fifa},
 {id:'kb-swim-1',sport:'swim',type:'exercise',title:'Кроль · повторные отрезки',summary:'Серия с длиной отрезка, временем, отдыхом и длиной бассейна.',body:'Задача: описать повторную плавательную серию.\n\nЗапишите стиль, число повторений, длину отрезка, ориентир времени и отдых. Укажите длину бассейна: она нужна для интерпретации результата.\n\nПосле выполнения сохраняйте время каждого повторения и наблюдения по технике. Рабочие параметры выбирает тренер под конкретного спортсмена.',equipment:'Бассейн · секундомер',volume:0},
 {id:'kb-swim-2',sport:'swim',type:'exercise',title:'Технический блок',summary:'Одна техническая задача и наблюдения тренера по каждому повторению.',body:'Задача: вынести техническую работу в отдельный блок занятия.\n\nЗапишите выбранный тренером технический элемент, способ выполнения и критерий наблюдения. Укажите дистанцию и оборудование, если оно требуется.\n\nПосле блока зафиксируйте, что получилось и к чему вернуться на следующем занятии. Это шаблон записи, без предписанной техники или универсальной дозировки.',equipment:'Бассейн · оборудование по задаче',volume:0},
 {id:'kb-run-plan',sport:'run',type:'template',title:'Бег · интервальный день',summary:'Разминка → повторные отрезки → заключительный блок → запись результатов.',body:'Демонстрационный вариант для настройки тренером:\n\n1. Разминка — 2 км.\n2. Основная серия — 4 × 600 м, темп и отдых задаёт тренер.\n3. Заключительный блок — 1,6 км.\n4. Запись времени отрезков и комментария спортсмена.\n\nПлановый объём бега — 6 км. Дистанции отдыха в этот пример не включены; если отдых бегом, скорректируйте общий объём.',equipment:'Размеченная дистанция · секундомер',volume:6},
 {id:'kb-football-plan',sport:'football',type:'template',title:'Футбол · передача и движение',summary:'Разминка с мячом → работа в парах → игровое применение → разбор.',body:'Демонстрационный план на 60 минут:\n\n1. Разминка с мячом — 10 минут.\n2. Передача и приём в движении — 15 минут.\n3. Игровой блок 4 × 4 — 25 минут.\n4. Заключительная часть и разбор — 10 минут.\n\nФокус наблюдения: обзор перед приёмом, направление первого касания, открывание после передачи. Дозировку и правила игры определяет тренер.',equipment:'8 игроков · мячи · фишки · манишки',volume:60},
 {id:'kb-swim-plan',sport:'swim',type:'template',title:'Плавание · кроль и техника',summary:'Разминка → технический блок → основная серия → заключительный блок.',body:'Демонстрационный вариант в бассейне 25 м:\n\n1. Разминка — 200 м.\n2. Технический блок — 4 × 50 м по задаче тренера.\n3. Основная серия — 4 × 100 м кролем; время и отдых задаёт тренер.\n4. Заключительный блок — 200 м.\n\nОбщий плановый объём — 1000 м. После выполнения запишите времена серий и наблюдения.',equipment:'Бассейн 25 м · секундомер',volume:1000},
 {id:'kb-tennis-1',sport:'tennis',type:'exercise',title:'Теннис · первый шаг',summary:'Карточка наблюдения за началом перемещения по сигналу тренера.',body:`Демопример для настройки тренером. Укажите исходную позицию, сигнал и направление перемещения.

Начните с калибровочного повторения: спортсмен объясняет задачу и показывает выполнение. Тренер выбирает скорость, число повторений и отдых.

После серии зафиксируйте наблюдение и следующую задачу.`,equipment:'Корт · фишки',volume:0},
 {id:'kb-tennis-plan',sport:'tennis',type:'template',title:'Теннис · ОФП перед кортом',summary:'Между турнирами: общий план группы с местом для индивидуальных изменений.',body:`Демопример на 45 минут, параметры подтверждает тренер.

1. Вводный блок — 10 минут: состояние группы, задача, калибровочный повтор.
2. Перемещения — 15 минут: первый шаг, направление и контроль техники.
3. Координация — 10 минут: работа по выбранным тренером сигналам.
4. Завершение — 10 минут: с учётом следующей работы на корте.

Контекст: между турнирами, ОФП до тенниса. После занятия сохраните факт, причину изменений и задачу на следующий раз.`,equipment:'Корт · фишки · секундомер',volume:45}
];
function safeVideo(url){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
const methodFields=[['levels','Уровни L1–L3 и критерии перехода'],['technique','Что контролировать в технике'],['mistakes','Типичные ошибки'],['easier','Как упростить упражнение']];
const demoMethod={levels:'L1 — знакомая задача с контролем тренера. L2 — самостоятельное выполнение той же задачи. L3 — добавление одного условия. Критерии перехода и число качественных повторений задаёт тренер.',technique:'Перед серией спортсмен показывает калибровочный повтор. Тренер записывает конкретный наблюдаемый критерий под задачу упражнения.',mistakes:'Потеря согласованного критерия, непонимание сигнала или порядка действий. Конкретные ошибки уточняются тренером.',easier:'Убрать одно дополнительное условие, уменьшить скорость или организовать работу с более частым контролем тренера.',video:''};
export const catalog=s=>materials.concat(s.knowledge?.custom||[]);
export function validateKnowledge(d){
 const fail=()=>{throw new Error('Проверьте формат библиотеки тренера. Изменения не сохранены.');},str=(v,max)=>typeof v==='string'&&v.length<=max;
 if(!d||!Array.isArray(d.custom)||d.custom.length>500||!Array.isArray(d.favorites)||d.favorites.length>600)fail();
 const ids=new Set(materials.map(x=>x.id));
 for(const x of d.custom){if(!x||!str(x.id,80)||!x.id||ids.has(x.id)||x.source!==undefined||!Object.hasOwn(sports,x.sport)||!['exercise','template'].includes(x.type)||!str(x.title,160)||!x.title.trim()||!str(x.summary,300)||!str(x.body,5000)||!x.body.trim()||!str(x.equipment,200)||!Number.isFinite(x.volume)||x.volume<0||x.volume>100000||(x.type==='template'&&x.volume<=0))fail();if(x.method!==undefined){if(!x.method||!['levels','technique','mistakes','easier','video'].every(k=>str(x.method[k],k==='video'?500:1000)))fail();if(x.method.video&&!safeVideo(x.method.video))fail();}ids.add(x.id);}
 if(d.favorites.some(x=>!ids.has(x))||new Set(d.favorites).size!==d.favorites.length)fail();return d;
}
let selectedSport='all',selectedType='all',query='',onlyFavorites=false;
export function filterMaterials(s,filters){const q=filters.query.trim().toLocaleLowerCase('ru-RU');return catalog(s).filter(x=>(filters.sport==='all'||x.sport===filters.sport)&&(filters.type==='all'||x.type===filters.type)&&(!filters.favorites||s.knowledge?.favorites.includes(x.id))&&[x.title,x.summary,x.body,x.equipment,sports[x.sport].name].join(' ').toLocaleLowerCase('ru-RU').includes(q));}
function cards(s){const list=filterMaterials(s,{sport:selectedSport,type:selectedType,query,favorites:onlyFavorites});return list.length?list.map(x=>`<article class="kb-card" style="--sport:${sports[x.sport].color}"><div class="kb-card-top"><span>${sports[x.sport].name}</span><button class="kb-star" data-action="kb-star" data-id="${esc(x.id)}" aria-label="В избранное: ${esc(x.title)}" aria-pressed="${!!s.knowledge?.favorites.includes(x.id)}">${s.knowledge?.favorites.includes(x.id)?'★':'☆'}</button></div><span class="kb-type">${x.type==='exercise'?'Упражнение':'Шаблон тренировки'}</span><h2>${esc(x.title)}</h2><p>${esc(x.summary)}</p><small>${esc(x.equipment)}</small><div class="kb-card-actions">${btn('Открыть','kb-open',x.id,'subtle')}${x.type==='template'?btn('В план →','kb-use',x.id,'secondary'):''}</div></article>`).join(''):'<div class="empty kb-empty">Материалы не найдены. Измените фильтры или добавьте свой материал.</div>';}
export function knowledgePage(s){const all=catalog(s);return `<div class="page-heading"><div><span class="eyebrow">Библиотека тренера</span><h1>Знания в работу.</h1><p>Упражнения и шаблоны для следующей тренировки.</p></div><div class="heading-actions">${btn('+ Упражнение','kb-new','exercise','secondary')}${btn('+ Шаблон','kb-new','template','')}</div></div><section class="kb-intro"><span class="kb-book" aria-hidden="true">▤</span><div><h2>От карточки упражнения к плану недели</h2><p>Откройте материал, настройте шаблон под свою задачу и добавьте его в спортивное пространство.</p></div><div class="kb-counts"><b>${all.filter(x=>x.type==='exercise').length}</b><span>упражнений</span><b>${all.filter(x=>x.type==='template').length}</b><span>шаблона</span></div></section><div class="kb-filters"><label>Вид спорта<select id="kb-sport"><option value="all">Все виды спорта</option>${Object.entries(sports).map(([k,c])=>`<option value="${k}" ${selectedSport===k?'selected':''}>${c.name}</option>`).join('')}</select></label><label>Тип материала<select id="kb-type"><option value="all">Все материалы</option><option value="exercise" ${selectedType==='exercise'?'selected':''}>Упражнения</option><option value="template" ${selectedType==='template'?'selected':''}>Шаблоны</option></select></label><label class="kb-search">Поиск<input id="kb-search" value="${esc(query)}" placeholder="Темп, кроль, передача…" type="search"></label><button class="button secondary kb-favorite-filter" data-action="kb-filter-star" aria-pressed="${onlyFavorites}">${onlyFavorites?'★':'☆'} Избранное</button></div><div id="kb-grid" class="kb-grid">${cards(s)}</div><p class="concept-note">Демоматериалы показывают структуру библиотеки. Тренер выбирает параметры под спортсмена. Свои материалы и избранное сохраняются в браузере и входят в экспорт.</p>`;}
export function knowledgeFilter(e,s){if(e.target.id==='kb-search'&&e.type!=='input')return false;if(!['kb-sport','kb-type','kb-search'].includes(e.target.id))return false;if(e.target.id==='kb-sport')selectedSport=e.target.value;if(e.target.id==='kb-type')selectedType=e.target.value;if(e.target.id==='kb-search')query=e.target.value;document.querySelector('#kb-grid').innerHTML=cards(s);return true;}
function materialForm(type,original,open,change,render){const x=original||{sport:selectedSport==='all'?'run':selectedSport,title:'',summary:'',body:'',equipment:'',volume:type==='template'?6:0};open(original?'Изменить материал':type==='exercise'?'Новое упражнение':'Новый шаблон',`<label>Вид спорта<select name="sport">${Object.entries(sports).map(([k,c])=>`<option value="${k}" ${x.sport===k?'selected':''}>${c.name}</option>`).join('')}</select></label>`+field('Название','title',x.title,'text','required maxlength="160"')+field('Краткое описание','summary',x.summary,'text','maxlength="300"')+`<label>Содержание и шаги<textarea name="body" required maxlength="5000">${esc(x.body)}</textarea></label>`+field('Участники и оборудование','equipment',x.equipment,'text','maxlength="200"')+(type==='exercise'?methodFields.map(([key,label])=>`<label>${label}<textarea name="${key}" maxlength="1000">${esc(x.method?.[key]||'')}</textarea></label>`).join('')+field('Видео · ссылка HTTPS','video',x.method?.video||'','url','maxlength="500"'):'')+(type==='template'?field('Объём: км для бега, минуты для футбола и тенниса, метры для плавания','volume',x.volume,'number','min="0.1" max="100000" step="0.1" required'):''),f=>{change('Материал библиотеки сохранён',n=>{n.knowledge??={custom:[],favorites:[]};const item={id:original?.id||crypto.randomUUID(),type,sport:f.get('sport'),title:f.get('title').trim(),summary:f.get('summary').trim(),body:f.get('body').trim(),equipment:f.get('equipment').trim(),volume:type==='template'?Number(f.get('volume')):0};if(type==='exercise')item.method=Object.fromEntries([...methodFields.map(([key])=>key),'video'].map(key=>[key,f.get(key).trim()]));if(original)Object.assign(n.knowledge.custom.find(t=>t.id===original.id),item);else n.knowledge.custom.push(item);});selectedSport=f.get('sport');selectedType='all';query='';onlyFavorites=false;render();});}
export function knowledgeAction(action,value,s,open,change,render){if(!action.startsWith('kb-'))return false;const item=catalog(s).find(x=>x.id===value);
 if(action==='kb-filter-star'){onlyFavorites=!onlyFavorites;render();}
 else if(action==='kb-new')materialForm(value==='template'?'template':'exercise',null,open,change,render);
 else if(action==='kb-star'){if(!item)throw new Error('Материал не найден.');change('Избранное обновлено',n=>{n.knowledge??={custom:[],favorites:[]};const fs=n.knowledge.favorites;n.knowledge.favorites=fs.includes(value)?fs.filter(x=>x!==value):fs.concat(value);});}
 else if(action==='kb-open'){if(!item)throw new Error('Материал не найден.');const own=!!s.knowledge?.custom.some(x=>x.id===value);open(item.title,`<div class="kb-detail-meta"><span class="badge green">${sports[item.sport].name}</span><span class="badge gray">${own?'Мой материал':item.source?'По материалам FIFA':'Демопример ТЕМП'}</span></div><p class="kb-detail-summary">${esc(item.summary)}</p><div class="kb-detail-body">${esc(item.body)}</div>${item.type==='exercise'?`<div class="exercise-method"><h3>Методическая карточка</h3>${!item.method?'<p class="form-hint">Демонстрационная структура. Критерии уточняет тренер.</p>':''}${methodFields.map(([key,label])=>`<h4>${label}</h4><p>${esc((item.method||demoMethod)[key])||'Не заполнено'}</p>`).join('')}${item.method?.video&&safeVideo(item.method.video)?`<a href="${esc(item.method.video)}" target="_blank" rel="noopener noreferrer">Видео упражнения ↗</a>`:''}</div>`:''}<p class="kb-equipment">${esc(item.equipment)}</p>${item.source?`<p><a href="${item.source}" target="_blank" rel="noopener noreferrer">Оригинал: FIFA Training Centre ↗</a></p>`:''}<div class="kb-detail-actions">${item.type==='template'?btn('Настроить и добавить в план','kb-use',value,''):''}${own?btn('Изменить','kb-edit',value,'secondary'):''}</div>`,null);}
 else if(action==='kb-edit'){const own=s.knowledge?.custom.find(x=>x.id===value);if(!own)throw new Error('Редактировать можно свои материалы.');materialForm(own.type,own,open,change,render);}
 else if(action==='kb-use'){if(!item||item.type!=='template')throw new Error('Шаблон не найден.');open('В план · '+item.title,`<p class="form-hint">Пространство: ${sports[item.sport].name}. Отредактируйте плановый объём и содержание перед добавлением.</p>`+field('Дата микроцикла','date','2026-10-06','date','min="2026-10-01" max="2026-10-07" required')+field('Объём, '+sports[item.sport].unit,'volume',item.volume,'number','min="0.1" max="100000" step="0.1" required')+`<label>План тренировки<textarea name="detail" required maxlength="5000">${esc(item.body)}</textarea></label>`,f=>{const day=f.get('date');if(day<'2026-10-01'||day>'2026-10-07')throw new Error('В демке доступен микроцикл 1–7 октября.');change('Шаблон добавлен в спортивный план',n=>{ensureSports(n);n.sports.active=item.sport;n.sports.spaces[item.sport].sessions.push({id:crypto.randomUUID(),date:day,title:item.title,detail:f.get('detail').trim(),volume:Number(f.get('volume')),status:'planned',result:'',materialId:item.id});});location.hash='sport';});}
 return true;
}
