const kinds=['run','football','swim'];
// ponytail: one fixed demo microcycle and sample rosters; add season navigation and roster editing for a real pilot.
export const sports={
 run:{name:'Лёгкая атлетика',icon:'↗',color:'#a35535',format:'Индивидуально и дистанционно',level:'Любители · подготовка к стартам',goal:'Осенний старт · 10 км',event:'Контрольный забег',date:'2026-10-18',unit:'км',caption:'План дистанций',theme:'Интервалы · 6 × 800 м',detail:'Темп 4:40/км · отдых 2 мин',focus:'Темп и устойчивость',test:'Контрольные 5 км',scores:['25:10','24:35','23:50'],members:['Анна Миронова','Михаил Орлов','Софья Белова'],roles:['10 км','Полумарафон','5 км']},
 football:{name:'Футбол',icon:'◉',color:'#3c7150',format:'Командная работа',level:'Юниоры U17 · соревновательная группа',goal:'Команда «Темп» · сезон 2026',event:'Темп — Север · матч',date:'2026-10-04',unit:'мин',caption:'План команды',theme:'Выход из прессинга · 4 × 4',detail:'90 мин · 8 игроков · малое поле',focus:'Взаимодействие линий',test:'Спринт 30 м',scores:['4,80 с','4,72 с','4,65 с'],members:['Артём Власов','Никита Серов','Даниил Егоров','Иван Крылов','Лев Смирнов','Максим Белов','Андрей Соколов','Роман Захаров'],roles:['Вратарь','Защитник','Защитник','Полузащитник','Полузащитник','Нападающий','Защитник','Нападающий']},
 swim:{name:'Плавание',icon:'≈',color:'#326e93',format:'Группы и индивидуальные занятия',level:'Любители · бассейн 25 м',goal:'Кроль · контрольные 100 м',event:'Контрольный заплыв',date:'2026-10-15',unit:'м',caption:'План серий',theme:'Кроль · 8 × 100 м',detail:'Отдых 30 с · бассейн 25 м',focus:'Техника и ровный темп',test:'100 м кроль',scores:['1:38,0','1:35,2','1:32,4'],members:['Дарья Соколова','Илья Лебедев','Вера Андреева','Павел Морозов'],roles:['Кроль · 100 м','Кроль · 200 м','Брасс · 100 м','Кроль · 100 м']}
};
export function seedSports(){return {active:'run',coach:{name:'Мария Лебедева',bio:'Тренер по физической подготовке. Индивидуальные планы, группы и команды.'},spaces:Object.fromEntries(kinds.map(k=>{const c=sports[k];return [k,{format:c.format,level:c.level,goal:c.goal,notes:'',sessions:[
 {id:k+'-1',date:'2026-10-01',title:c.theme,detail:c.detail,volume:k==='run'?8:k==='football'?90:2500,status:'planned',result:''},
 {id:k+'-2',date:'2026-10-03',title:k==='run'?'Длительный бег':k==='football'?'Тактика · стандартные положения':'Техника · работа ног',detail:k==='run'?'12 км · спокойный темп':k==='football'?'90 мин · вся группа':'10 × 50 м · доска',volume:k==='run'?12:k==='football'?90:2000,status:'planned',result:''},
 {id:k+'-3',date:'2026-10-05',title:k==='run'?'Восстановительный бег':k==='football'?'Восстановление после матча':'Кроль · аэробные серии',detail:k==='run'?'6 км · ровное усилие':k==='football'?'45 мин · подвижность и лёгкая работа':'4 × 500 м · ровный темп',volume:k==='run'?6:k==='football'?45:2000,status:'planned',result:''}
 ]}];}))};}
export function validateSports(d){
 const str=(v,max)=>typeof v==='string'&&v.length<=max,fail=()=>{throw new Error('Проверьте данные спортивных пространств. Изменения не сохранены.');};
 if(!d||!kinds.includes(d.active)||!d.coach||!str(d.coach.name,80)||!d.coach.name.trim()||!str(d.coach.bio,1000)||!d.spaces)fail();
 const ids=new Set();
 for(const k of kinds){const w=d.spaces[k];if(!w||!str(w.format,120)||!str(w.level,160)||!str(w.goal,200)||!str(w.notes,2000)||!Array.isArray(w.sessions)||w.sessions.length>500)fail();
 for(const x of w.sessions){if(!x||!str(x.id,80)||!x.id||ids.has(x.id)||!str(x.title,160)||!x.title.trim()||!str(x.detail,5000)||!str(x.result,1000)||!['planned','done'].includes(x.status)||!Number.isFinite(x.volume)||x.volume<=0||x.volume>100000||typeof x.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x.date))fail();const dt=new Date(x.date+'T12:00:00Z');if(Number.isNaN(dt.getTime())||dt.toISOString().slice(0,10)!==x.date)fail();if(x.status==='done'&&!x.result.trim())fail();ids.add(x.id);}}
 return d;
}
const data=s=>s.sports||seedSports();
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const btn=(text,action,id='',type='secondary')=>`<button type="button" class="button ${type}" data-action="${action}" data-id="${esc(id)}">${text}</button>`;
export const field=(label,name,value,type='text',attrs='')=>`<label>${label}<input name="${name}" value="${esc(value)}" type="${type}" ${attrs}></label>`;
const date=d=>new Date(d+'T12:00:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'UTC'});
function drawing(k){return k==='football'?'<rect x="15" y="15" width="250" height="170" rx="3"/><path d="M140 15V185 M15 55H55V145H15 M265 55H225V145H265"/><circle cx="140" cy="100" r="30"/><circle class="ball" cx="183" cy="72" r="5"/>':k==='swim'?'<path d="M15 35H265 M15 65H265 M15 95H265 M15 125H265 M15 155H265 M15 185H265"/><path class="ball" d="M65 80H135 M170 110H230 M90 140H190"/>':'<rect x="20" y="20" width="240" height="165" rx="80"/><rect x="35" y="35" width="210" height="135" rx="65"/><rect x="50" y="50" width="180" height="105" rx="50"/><path d="M140 50V155"/><circle class="ball" cx="210" cy="148" r="5"/>';}
export function sportPage(s){const d=data(s),k=d.active,c=sports[k],w=d.spaces[k],ss=w.sessions.slice().sort((a,b)=>a.date.localeCompare(b.date)),total=ss.reduce((n,x)=>n+x.volume,0),done=ss.filter(x=>x.status==='done'),actual=done.reduce((n,x)=>n+x.volume,0);return `
 <div class="sport-switch" role="group" aria-label="Спортивное пространство">${kinds.map(key=>`<button data-action="sport-switch" data-id="${key}" aria-pressed="${key===k}" class="${key===k?'selected':''}"><span>${sports[key].icon}</span>${sports[key].name}</button>`).join('')}<a href="#coach">Профиль тренера ↗</a></div>
 <section class="sport-hero" style="--sport:${c.color}"><div><span class="eyebrow">${esc(w.format)} · демопространство</span><h1>${c.name}</h1><p>${esc(w.goal)}</p><div class="sport-coach"><span class="avatar">${esc(d.coach.name.charAt(0))}</span><div><b>${esc(d.coach.name)}</b><small>${esc(w.level)}</small></div></div></div><svg viewBox="0 0 280 205" aria-hidden="true">${drawing(k)}</svg><div class="sport-event"><span>Следующая цель</span><b>${c.event}</b><strong>${date(c.date)}</strong><small>Демонстрационный календарь</small></div></section>
 <div class="sport-layout"><div><section class="panel sport-plan"><div class="panel-head"><div><h2>${c.caption}</h2><span>1–7 октября · микроцикл</span></div>${btn('+ Тренировка','sport-new',k,'')}</div><div class="week-strip">${['Чт','Пт','Сб','Вс','Пн','Вт','Ср'].map((day,i)=>`<div class="${ss.some(x=>x.date==='2026-10-0'+(i+1))?'training-day':''}"><span>${day}</span><b>${i+1}</b><i></i></div>`).join('')}</div>${ss.map(x=>`<div class="sport-session"><div class="sport-date">${date(x.date)}<small>${x.status==='done'?'Выполнено ✓':'План'}</small></div><div><h3>${esc(x.title)}</h3><p>${esc(x.detail)}</p><span>${x.volume} ${c.unit}</span>${x.result?`<p class="sport-result">${esc(x.result)}</p>`:''}</div>${btn(x.status==='done'?'Результат':'Записать результат','sport-result',x.id,x.status==='done'?'subtle':'secondary')}</div>`).join('')}</section>
 <section class="panel sport-roster"><div class="panel-head"><div><h2>${k==='football'?'Состав команды':'Спортсмены'}</h2><span>${c.members.length} · демонстрационная группа</span></div></div>${c.members.map((name,i)=>`<button class="sport-member" data-action="sport-athlete" data-id="${i}"><span class="avatar tone-${i%4}">${name.split(' ').map(n=>n[0]).join('')}</span><span><b>${name}</b><small>${c.roles[i]}</small></span><span>${i===0?c.scores.at(-1):'Открыть'} ↗</span></button>`).join('')}</section></div>
 <div><section class="panel sport-volume"><div class="panel-head"><h2>План и выполнение</h2></div><div class="padded"><span>Объём микроцикла · 1–7 октября</span><div class="volume-number">${actual} <small>/ ${total} ${c.unit}</small></div><div class="package-meter"><i style="width:${total?actual/total*100:0}%"></i></div><p>${done.length} из ${ss.length} тренировок выполнено</p></div></section><section class="panel sport-progress"><div class="panel-head"><div><h2>Контрольный результат</h2><span>${c.members[0]} · ${c.test}</span></div></div><div class="padded"><b class="sport-score">${c.scores.at(-1)}</b><div class="result-timeline">${c.scores.map((v,i)=>`<div><small>${['3 сен','17 сен','30 сен'][i]}</small><b>${v}</b></div>`).join('')}</div><p>Демонстрационная история тестов</p>${btn('Карточка спортсмена','sport-athlete','0','subtle')}</div></section><section class="panel sport-notes"><div class="panel-head"><h2>Фокус микроцикла</h2>${btn('Изменить','sport-notes',k,'subtle')}</div><div class="padded"><h3>${c.focus}</h3><p>${esc(w.notes)||'После каждой тренировки записывайте факт выполнения и наблюдения для следующего занятия.'}</p><span class="badge gray">Пример плана для демонстрации</span></div></section></div></div>`;}
export function coachPage(s){const d=data(s);return `<div class="page-heading"><div><span class="eyebrow">Мой профиль</span><h1>${esc(d.coach.name)}</h1><p>${esc(d.coach.bio)}</p></div>${btn('Изменить профиль','coach-edit','','')}</div><section class="coach-intro"><span class="avatar">${esc(d.coach.name.charAt(0))}</span><div><h2>Один тренер. Три направления.</h2><p>Свои спортсмены, формат занятий и цели подготовки в каждом пространстве.</p></div></section><div class="coach-spaces">${kinds.map(k=>{const c=sports[k],w=d.spaces[k];return `<section class="panel coach-space" style="--sport:${c.color}"><span class="space-symbol">${c.icon}</span><h2>${c.name}</h2><p>${esc(w.format)}</p><dl><dt>Спортсмены</dt><dd>${esc(w.level)}</dd><dt>Цель подготовки</dt><dd>${esc(w.goal)}</dd><dt>Что записываем</dt><dd>${k==='run'?'Дистанции, темп и интервалы':k==='football'?'Игровые упражнения, состав и матчи':'Стиль, серии, дистанции и отдых'}</dd></dl>${btn('Настроить','coach-space',k,'subtle')}${btn('Открыть пространство','sport-switch',k,'secondary')}</section>`;}).join('')}</div><p class="concept-note">Демопрофиль вымышленный. Спортивные планы показывают концепцию продукта; административные разделы доступны в общем кабинете.</p>`;}
export function sportAction(action,value,s,open,change){if(!action.startsWith('sport-')&&!action.startsWith('coach-'))return false;const d=data(s),k=d.active,c=sports[k];const update=(text,fn)=>change(text,n=>{n.sports??=seedSports();fn(n.sports);});
 if(action==='sport-switch'){if(!kinds.includes(value))throw new Error('Пространство не найдено.');update('Спортивное пространство открыто',n=>n.active=value);location.hash='sport';}
 else if(action==='coach-edit')open('Профиль тренера',field('Имя','name',d.coach.name,'text','required maxlength="80"')+`<label>О себе<textarea name="bio" maxlength="1000">${esc(d.coach.bio)}</textarea></label>`,f=>update('Профиль тренера обновлён',n=>{n.coach={name:f.get('name').trim(),bio:f.get('bio').trim()};}));
 else if(action==='coach-space'){const w=d.spaces[value];if(!w)throw new Error('Пространство не найдено.');open('Настройки · '+sports[value].name,field('Формат работы','format',w.format,'text','required maxlength="120"')+field('Уровень и группа','level',w.level,'text','required maxlength="160"')+field('Цель подготовки','goal',w.goal,'text','required maxlength="200"'),f=>update('Направление обновлено',n=>Object.assign(n.spaces[value],{format:f.get('format').trim(),level:f.get('level').trim(),goal:f.get('goal').trim()})));}
 else if(action==='sport-notes')open('Фокус микроцикла',`<label>Наблюдения и следующие шаги<textarea name="notes" maxlength="2000">${esc(d.spaces[k].notes)}</textarea></label>`,f=>update('Заметки сохранены',n=>n.spaces[k].notes=f.get('notes').trim()));
 else if(action==='sport-new')open('Тренировка · '+c.name,field('Название','title',c.theme,'text','required maxlength="160"')+field(k==='run'?'Интервалы, темп и отдых':k==='football'?'Упражнения и состав':'Стиль, серии и отдых','detail',c.detail,'text','maxlength="300"')+`<div class="form-grid">${field('Дата микроцикла','date','2026-10-06','date','min="2026-10-01" max="2026-10-07" required')}${field('Объём, '+c.unit,'volume',k==='run'?6:k==='football'?60:1500,'number','min="0.1" max="100000" step="0.1" required')}</div>`,f=>{const day=f.get('date');if(day<'2026-10-01'||day>'2026-10-07')throw new Error('В демке планируем микроцикл 1–7 октября.');update('Тренировка добавлена',n=>n.spaces[k].sessions.push({id:crypto.randomUUID(),title:f.get('title').trim(),detail:f.get('detail').trim(),date:day,volume:Number(f.get('volume')),status:'planned',result:''}));});
 else if(action==='sport-result'){const x=d.spaces[k].sessions.find(x=>x.id===value);if(!x)throw new Error('Тренировка не найдена.');open('Результат · '+x.title,`<p class="form-hint">${k==='run'?'Запишите дистанцию, фактический темп и ощущения.':k==='football'?'Запишите состав, выполненные упражнения и наблюдения по игре.':'Запишите время серий, стиль и наблюдения по технике.'} Отметка относится к спортивному плану.</p><label>Что выполнено<textarea name="result" required maxlength="1000">${esc(x.result)}</textarea></label>`,f=>update('Результат тренировки сохранён',n=>Object.assign(n.spaces[k].sessions.find(t=>t.id===value),{result:f.get('result').trim(),status:'done'})),'Сохранить результат');}
 else if(action==='sport-athlete'){const i=Number(value);if(!Number.isInteger(i)||i<0||i>=c.members.length)throw new Error('Спортсмен не найден.');open(c.members[i],`<span class="badge green">${c.roles[i]}</span><h3 class="athlete-title">${i===0?c.test:'Цель подготовки'}</h3><p>${i===0?c.scores.join(' → '):esc(d.spaces[k].goal)}</p><h3>Ближайшая цель</h3><p>${c.event} · ${date(c.date)}</p><p class="form-hint">Демонстрационная карточка. Результаты контрольных тестов вымышлены; журнал тренировок заполняется на экране пространства.</p>`,null);}
 return true;
}
